changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - question
      - wontfix
      - release
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: Features
      labels:
        - feature
    - title: Improvements
      labels:
        - improvement
        - performance
    - title: Bug Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Dependencies
      labels:
        - dependencies
    - title: Maintenance
      labels:
        - maintenance
    - title: Other Changes
      labels:
        - "*"
